

# See for example https://github.com/jobindjohn/obsidian-publish-mkdocs on how to
# publish Obsidian notes via MkDocs. See https://www.codeinsideout.com/blog/site-setup/create-site-project/#extend-the-theme
# for further information on customizations.

site_name: Wiki of ConFusion
site_url: http://confusion.nmbr73.net/
repo_url: https://github.com/nmbr73/Kernfusion/
repo_name: Kernfusion
edit_uri: blob/main/Wiki/ # 'edit_uri: edit/main/Wiki/' works only if signed in and granted access


# nav:
#   - Home: index.md
#   - About.md
#   - ...


# nav:
#   - Home: index.html
#   - Kartaverse Workflows:
#     - Kartaverse Workflows/index.md
#     - Kartaverse Workflows/Kartaverse Workflows.md
#     - Kartaverse Workflows/Creating Volumetric NeRFs.md
#     - Kartaverse Workflows/Creating ST Maps.md
#     - Render Fusion Comps in Houdini TOPs.md
#     - SketchFab in VR Via QuestLink.md
#     - Troubleshooting Guide for Fusion Studio Freeze Ups.md
#     - YouTube 360 to Equirectangular Conversions.md
#     - Jupyter Notebook for Resolve/Fusion: Jupyter Notebook for Resolve_Fusion.md
#     - Domemaster Photoshop Actions Pack.md
#     - DEV OpenDisplayXR VDD (Virtual Device Driver).md
#     - DEV The Ultimate Guide to OpenUSD Pipeline Development.md
#     - DEV Building an Effective nVP (Neural Virtual Production) Sound Stage.md
#     - KickAss ShaderZ for Fusion.md

# nav:
#     - Home: README.md
#     - About: DCTL.md
#     - Nochmal:
#       - README.md
#       - DCTL.md
#     - Featured: Featured Articles.md
#     - Woanders: Script/Script-Libraries.md

theme:
  name: 'material'
  # name: bootstrap386

  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      # scheme: wsl
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences

# Extensions
markdown_extensions:

  - nl2br # needed by 'callouts' cause newlines to be treated as hard breaks; like StackOverflow and GitHub flavored Markdown do
  - admonition # aka callouts; needed by 'callouts'
  - pymdownx.details # needed by 'callouts'; html5 <details><summary> for collapsible element

  - def_list # syntax: https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - attr_list # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - md_in_html
  - footnotes
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde # subscript via ~
  - pymdownx.caret  # superscript via ^
  - pymdownx.keys # to display keyboard shortcuts ++ctrl+alt+del++
  - pymdownx.mark # to mark text using ==some text==
  - pymdownx.smartsymbols # to render -->, <--, =/=, (c), 1st, 1/4, etc.
#  - pymdownx.inlinehilite # `#!py3 code`
  - pymdownx.highlight:
#      anchor_linenums: true
# - pymdownx.magiclink
  - pymdownx.saneheaders # to force header to have a space after the '#''
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


plugins:
  - search
  - roamlinks # to allow wiki-markup links [[...]] as used in Obsidian; https://github.com/Jackiexiao/mkdocs-roamlinks-plugin
  - callouts # converts Obsidian callouts into MkDocs admonitions; https://pypi.org/project/mkdocs-callouts/
  - awesome-pages: # allows .pages files in directories for navigation; https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
      collapse_single_pages: true
  - tags:
      tags_file: Categories.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets_wiki/stylesheets/extra.css


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nmbr73/Kernfusion
      name: Kernfusion on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Zb48E4z3Pg
      name: Fusion Developers Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/nmbr73/videos
      name: nmbr73 on YouTube (place some reasonable link in here)
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nmbr73
      name: nmbr73 on Twitter (place some reasonable link in here)
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/nmbr73/
      name: nmbr73 on IG (place some reasonable link in here)
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/nmbr73
      name: nmbr73 on Reddit (place some reasonable link in here)
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/nmbr73
      name: nmbr73 on Twitch (place some reasonable link in here)
    - icon: fontawesome/brands/tumblr
      link: https://www.tumblr.com/nmbr73
      name: nmbr73 on tumblr (place some reasonable link in here)
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.de/nmbr73/
      name: nmbr73 on Pinterest (place some reasonable link in here)


