name: ci
on:
  push:
    branches:
      - main
    paths:
      - Wiki/**.md
      - .github/workflows/wiki2ghpages.yml
      - mkdocs.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Instal mkdocs and plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-callouts
          pip install mkdocs-awesome-pages-plugin
      - name: Run mkdocs
        run: |
          mv Wiki docs
          mkdocs gh-deploy --force
